# Generated by Django 5.2 on 2026-01-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_business_id_alter_serviceoffering_id'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When this subscription period ended (for history tracking)', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='business.business'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_subscriptions', to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('ended', 'Ended')], default='incomplete', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['business', 'status', '-created_at'], name='subscriptio_busines_067aba_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__74f5da_idx'),
        ),
    ]
