# Generated by Django 5.2 on 2025-12-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_businessconfiguration_ai_model_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
