# Generated by Django 5.2 on 2026-02-12 17:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_business_id_alter_serviceoffering_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfiguration',
            name='staff_pay_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default percentage of booking revenue paid to staff (e.g., 50.00 for 50%)', max_digits=5),
        ),
    ]
