"""
Django settings for services_ai project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Plugins directory
PLUGINS_DIR = os.path.join(BASE_DIR, 'plugins')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-1234567890')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv('DJANGO_DEBUG') == 'True' else False

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    'corsheaders',  # For CORS support (widget embedding)

    # Custom apps
    'admin_dashboard.apps.AdminDashboardConfig',
    'subscription.apps.SubscriptionConfig',
    'ai_agent.apps.AiAgentConfig',
    'bookings.apps.BookingsConfig',
    'invoices.apps.InvoicesConfig',
    'leads.apps.LeadsConfig',
    'retell_agent.apps.RetellAgentConfig',
    'core.apps.CoreConfig',
    'business.apps.BusinessConfig',
    'accounts.apps.AccountsConfig',
    'integration.apps.IntegrationConfig',
    'dashboard.apps.DashboardConfig',
    'notifications.apps.NotificationsConfig',
    'analytics.apps.AnalyticsConfig',
    'staff.apps.StaffConfig',
    'customer.apps.CustomerConfig',
    'ai_website.apps.AiWebsiteConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (must be before CommonMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'subscription.middleware.SubscriptionRequiredMiddleware',  # Check subscription status
    'staff.middleware.StaffAccessMiddleware',
]

ROOT_URLCONF = 'services_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'services_ai.wsgi.application'
ASGI_APPLICATION = "services_ai.asgi.application"

import dj_database_url

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG == True:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(default=os.getenv('DATABASE_URL')),
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




BASE_URL = 'https://bookyai.up.railway.app'
SITE_URL = 'https://bookyai.up.railway.app'
# OPENAI
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# GEMINI
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://bookyai.up.railway.app',
    'https://63ed-37-111-171-174.ngrok-free.app',
]

# Allow iframes from same origin for template preview
X_FRAME_OPTIONS = 'SAMEORIGIN'

Q_CLUSTER = {
    'name': 'bookyai',
    'workers': 8,
    'recycle': 500,
    'timeout': 300,
    'retry': 3600,
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 4,
    'label': 'Django Q2',
    'orm': 'default',
    'max_attempts': 3,
}





STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')




RETELL_BASE_URL = os.getenv('RETELL_BASE_URL')
RETELL_API_KEY = os.getenv('RETELL_API_KEY')


# Django EventStream Configuration




EMAILIT_API_KEY = os.getenv('EMAILIT_API_KEY')


# CORS Configuration for Booking Widget
# Allow all origins for development (restrict in production)
CORS_ALLOW_ALL_ORIGINS = True

# Alternative: Allow specific origins only (recommended for production)
# CORS_ALLOWED_ORIGINS = [
#     "https://yourdomain.com",
#     "https://third-party-site.com",
# ]

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allow specific HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow specific headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


