# Generated by Django 5.2 on 2026-02-12 17:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_customer'),
        ('business', '0014_businessconfiguration_staff_pay_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPayout',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('period_start', models.DateField(help_text='Start date of the payout period')),
                ('period_end', models.DateField(help_text='End date of the payout period')),
                ('total_bookings', models.PositiveIntegerField(default=0, help_text='Number of completed bookings in this period')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue from all bookings in this period', max_digits=10)),
                ('payout_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of revenue paid to staff (e.g., 50.00 for 50%)', max_digits=5)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be paid to staff (total_revenue * payout_percentage / 100)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, help_text='Date when the payout was marked as paid', null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Method of payment (e.g., Bank Transfer, Cash, Check)', max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Reference number or transaction ID', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payout', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payouts', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payouts', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='bookings.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Payout',
                'verbose_name_plural': 'Staff Payouts',
                'ordering': ['-period_end', '-created_at'],
                'unique_together': {('staff_member', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='StaffPayoutBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_revenue', models.DecimalField(decimal_places=2, help_text='Revenue from this booking', max_digits=10)),
                ('staff_earning', models.DecimalField(decimal_places=2, help_text="Staff member's earning from this booking (booking_revenue * payout_percentage / 100)", max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payouts', to='bookings.booking')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_bookings', to='bookings.staffpayout')),
            ],
            options={
                'verbose_name': 'Staff Payout Booking',
                'verbose_name_plural': 'Staff Payout Bookings',
                'ordering': ['booking__booking_date', 'booking__start_time'],
                'unique_together': {('payout', 'booking')},
            },
        ),
    ]
