# Generated by Django 5.2 on 2026-02-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_staffpayout_staffpayoutbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpayout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff Payout', 'verbose_name_plural': 'Staff Payouts'},
        ),
        migrations.AlterUniqueTogether(
            name='staffpayout',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffpayout',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='staff_payouts', to='bookings.booking'),
        ),
        migrations.DeleteModel(
            name='StaffPayoutBooking',
        ),
        migrations.RemoveField(
            model_name='staffpayout',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='staffpayout',
            name='payout_amount',
        ),
        migrations.RemoveField(
            model_name='staffpayout',
            name='payout_percentage',
        ),
        migrations.RemoveField(
            model_name='staffpayout',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='staffpayout',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='staffpayout',
            name='total_bookings',
        ),
        migrations.RemoveField(
            model_name='staffpayout',
            name='total_revenue',
        ),
    ]
