# Generated by Django 5.2 on 2026-02-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_business_id_alter_serviceoffering_id'),
        ('notifications', '0002_alter_notification_related_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='business.business'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
